export const monetaryBadgeIds = {
    LOCAL_MULTI_SIG_CONTROLLER_BADGE: 1,
    RESERVE_DELEGATE: 2,
    RESERVE_VETO_DELEGATE: 3,
    TOPOLOGY_DELEGATE: 4,
    FOOD_FOREST_ECOLOGY_DELEGATE: 5,
    WEATHER_STATION_ECOLOGY_DELEGATE: 6,
    RESERVE_ARBITRAGEUR: 7,
    LOCAL_MULTI_SIG_MEMBER: 8,
    FOOD_FOREST_MULTI_SIG_MEMBER: 9,
    ECOLOGY_DELEGATE_PROPOSER: 10,
  };
  
  // badges and associated roles used on kolektivo badger (global)
export const kolektivoBadgeIds = {
    TREASURY_DELEGATE: 101,
    TREASURY_VETO_DELEGATE: 102,
    TREASURY_ARBITRAGEUR: 103,
    KOLEKTIVO_MULTI_SIG_MEMBER: 104,
  };